# .goreleaser.yml
version: 2

project_name: haproxy-configurator

# Build configuration
builds:
  - id: haproxy-configurator
    main: ./cmd/server/main.go
    binary: haproxy-configurator
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

# No Docker configuration - CLI tool only

# Archive configuration (v2 format)
archives:
  - id: haproxy-configurator
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - haproxy-configurator
    files:
      - README.md
      - LICENSE*

# Checksum
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

# Changelog
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"

# Release configuration
release:
  github:
    owner: bear-san
    name: haproxy-configurator
  draft: false
  prerelease: auto
  name_template: "Release {{ .Version }}"