version: '3.8'

services:
  haproxy-configurator:
    build:
      context: ..
      dockerfile: dev/Dockerfile.dev
    ports:
      - "50051:50051"
    environment:
      - HAPROXY_API_URL=http://haproxy:5555
      - HAPROXY_API_USERNAME=admin
      - HAPROXY_API_PASSWORD=admin
    depends_on:
      - haproxy
    networks:
      - haproxy-configurator

  haproxy:
    image: haproxy:2.8-alpine
    ports:
      - "80:80"
      - "443:443"
      - "5555:5555"  # Data Plane API
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    command: >
      sh -c "haproxy -f /usr/local/etc/haproxy/haproxy.cfg -db"
    networks:
      - haproxy-configurator

networks:
  haproxy-configurator:
    driver: bridge