// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: backend.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BackendBalance represents load balancing configuration for backend
type BackendBalance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Algorithm     string                 `protobuf:"bytes,1,opt,name=algorithm,proto3" json:"algorithm,omitempty"` // first, hash, random, roundrobin
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackendBalance) Reset() {
	*x = BackendBalance{}
	mi := &file_backend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendBalance) ProtoMessage() {}

func (x *BackendBalance) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendBalance.ProtoReflect.Descriptor instead.
func (*BackendBalance) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{0}
}

func (x *BackendBalance) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

// Backend represents a HAProxy backend configuration
type Backend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Balance       *BackendBalance        `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Mode          string                 `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"` // tcp, http
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Backend) Reset() {
	*x = Backend{}
	mi := &file_backend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Backend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Backend) ProtoMessage() {}

func (x *Backend) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Backend.ProtoReflect.Descriptor instead.
func (*Backend) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{1}
}

func (x *Backend) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Backend) GetBalance() *BackendBalance {
	if x != nil {
		return x.Balance
	}
	return nil
}

func (x *Backend) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Backend) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type CreateBackendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Backend       *Backend               `protobuf:"bytes,2,opt,name=backend,proto3" json:"backend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBackendRequest) Reset() {
	*x = CreateBackendRequest{}
	mi := &file_backend_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBackendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBackendRequest) ProtoMessage() {}

func (x *CreateBackendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBackendRequest.ProtoReflect.Descriptor instead.
func (*CreateBackendRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBackendRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *CreateBackendRequest) GetBackend() *Backend {
	if x != nil {
		return x.Backend
	}
	return nil
}

type CreateBackendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Backend       *Backend               `protobuf:"bytes,1,opt,name=backend,proto3" json:"backend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBackendResponse) Reset() {
	*x = CreateBackendResponse{}
	mi := &file_backend_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBackendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBackendResponse) ProtoMessage() {}

func (x *CreateBackendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBackendResponse.ProtoReflect.Descriptor instead.
func (*CreateBackendResponse) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{3}
}

func (x *CreateBackendResponse) GetBackend() *Backend {
	if x != nil {
		return x.Backend
	}
	return nil
}

type GetBackendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBackendRequest) Reset() {
	*x = GetBackendRequest{}
	mi := &file_backend_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBackendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBackendRequest) ProtoMessage() {}

func (x *GetBackendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBackendRequest.ProtoReflect.Descriptor instead.
func (*GetBackendRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{4}
}

func (x *GetBackendRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *GetBackendRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetBackendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Backend       *Backend               `protobuf:"bytes,1,opt,name=backend,proto3" json:"backend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBackendResponse) Reset() {
	*x = GetBackendResponse{}
	mi := &file_backend_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBackendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBackendResponse) ProtoMessage() {}

func (x *GetBackendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBackendResponse.ProtoReflect.Descriptor instead.
func (*GetBackendResponse) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{5}
}

func (x *GetBackendResponse) GetBackend() *Backend {
	if x != nil {
		return x.Backend
	}
	return nil
}

type ListBackendsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBackendsRequest) Reset() {
	*x = ListBackendsRequest{}
	mi := &file_backend_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBackendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBackendsRequest) ProtoMessage() {}

func (x *ListBackendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBackendsRequest.ProtoReflect.Descriptor instead.
func (*ListBackendsRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{6}
}

func (x *ListBackendsRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type ListBackendsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Backends      []*Backend             `protobuf:"bytes,1,rep,name=backends,proto3" json:"backends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBackendsResponse) Reset() {
	*x = ListBackendsResponse{}
	mi := &file_backend_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBackendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBackendsResponse) ProtoMessage() {}

func (x *ListBackendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBackendsResponse.ProtoReflect.Descriptor instead.
func (*ListBackendsResponse) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{7}
}

func (x *ListBackendsResponse) GetBackends() []*Backend {
	if x != nil {
		return x.Backends
	}
	return nil
}

type UpdateBackendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Backend       *Backend               `protobuf:"bytes,3,opt,name=backend,proto3" json:"backend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBackendRequest) Reset() {
	*x = UpdateBackendRequest{}
	mi := &file_backend_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBackendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBackendRequest) ProtoMessage() {}

func (x *UpdateBackendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBackendRequest.ProtoReflect.Descriptor instead.
func (*UpdateBackendRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateBackendRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *UpdateBackendRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateBackendRequest) GetBackend() *Backend {
	if x != nil {
		return x.Backend
	}
	return nil
}

type UpdateBackendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Backend       *Backend               `protobuf:"bytes,1,opt,name=backend,proto3" json:"backend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBackendResponse) Reset() {
	*x = UpdateBackendResponse{}
	mi := &file_backend_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBackendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBackendResponse) ProtoMessage() {}

func (x *UpdateBackendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBackendResponse.ProtoReflect.Descriptor instead.
func (*UpdateBackendResponse) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateBackendResponse) GetBackend() *Backend {
	if x != nil {
		return x.Backend
	}
	return nil
}

type DeleteBackendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBackendRequest) Reset() {
	*x = DeleteBackendRequest{}
	mi := &file_backend_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBackendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBackendRequest) ProtoMessage() {}

func (x *DeleteBackendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBackendRequest.ProtoReflect.Descriptor instead.
func (*DeleteBackendRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteBackendRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *DeleteBackendRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteBackendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBackendResponse) Reset() {
	*x = DeleteBackendResponse{}
	mi := &file_backend_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBackendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBackendResponse) ProtoMessage() {}

func (x *DeleteBackendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBackendResponse.ProtoReflect.Descriptor instead.
func (*DeleteBackendResponse) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{11}
}

var File_backend_proto protoreflect.FileDescriptor

const file_backend_proto_rawDesc = "" +
	"\n" +
	"\rbackend.proto\x12\n" +
	"haproxy.v1\".\n" +
	"\x0eBackendBalance\x12\x1c\n" +
	"\talgorithm\x18\x01 \x01(\tR\talgorithm\"w\n" +
	"\aBackend\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x124\n" +
	"\abalance\x18\x02 \x01(\v2\x1a.haproxy.v1.BackendBalanceR\abalance\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\tR\x04mode\"l\n" +
	"\x14CreateBackendRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12-\n" +
	"\abackend\x18\x02 \x01(\v2\x13.haproxy.v1.BackendR\abackend\"F\n" +
	"\x15CreateBackendResponse\x12-\n" +
	"\abackend\x18\x01 \x01(\v2\x13.haproxy.v1.BackendR\abackend\"N\n" +
	"\x11GetBackendRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"C\n" +
	"\x12GetBackendResponse\x12-\n" +
	"\abackend\x18\x01 \x01(\v2\x13.haproxy.v1.BackendR\abackend\"<\n" +
	"\x13ListBackendsRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\"G\n" +
	"\x14ListBackendsResponse\x12/\n" +
	"\bbackends\x18\x01 \x03(\v2\x13.haproxy.v1.BackendR\bbackends\"\x80\x01\n" +
	"\x14UpdateBackendRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12-\n" +
	"\abackend\x18\x03 \x01(\v2\x13.haproxy.v1.BackendR\abackend\"F\n" +
	"\x15UpdateBackendResponse\x12-\n" +
	"\abackend\x18\x01 \x01(\v2\x13.haproxy.v1.BackendR\abackend\"Q\n" +
	"\x14DeleteBackendRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x17\n" +
	"\x15DeleteBackendResponseB<Z:github.com/bear-san/haproxy-network-manager/pkg/haproxy/v1b\x06proto3"

var (
	file_backend_proto_rawDescOnce sync.Once
	file_backend_proto_rawDescData []byte
)

func file_backend_proto_rawDescGZIP() []byte {
	file_backend_proto_rawDescOnce.Do(func() {
		file_backend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backend_proto_rawDesc), len(file_backend_proto_rawDesc)))
	})
	return file_backend_proto_rawDescData
}

var file_backend_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_backend_proto_goTypes = []any{
	(*BackendBalance)(nil),        // 0: haproxy.v1.BackendBalance
	(*Backend)(nil),               // 1: haproxy.v1.Backend
	(*CreateBackendRequest)(nil),  // 2: haproxy.v1.CreateBackendRequest
	(*CreateBackendResponse)(nil), // 3: haproxy.v1.CreateBackendResponse
	(*GetBackendRequest)(nil),     // 4: haproxy.v1.GetBackendRequest
	(*GetBackendResponse)(nil),    // 5: haproxy.v1.GetBackendResponse
	(*ListBackendsRequest)(nil),   // 6: haproxy.v1.ListBackendsRequest
	(*ListBackendsResponse)(nil),  // 7: haproxy.v1.ListBackendsResponse
	(*UpdateBackendRequest)(nil),  // 8: haproxy.v1.UpdateBackendRequest
	(*UpdateBackendResponse)(nil), // 9: haproxy.v1.UpdateBackendResponse
	(*DeleteBackendRequest)(nil),  // 10: haproxy.v1.DeleteBackendRequest
	(*DeleteBackendResponse)(nil), // 11: haproxy.v1.DeleteBackendResponse
}
var file_backend_proto_depIdxs = []int32{
	0, // 0: haproxy.v1.Backend.balance:type_name -> haproxy.v1.BackendBalance
	1, // 1: haproxy.v1.CreateBackendRequest.backend:type_name -> haproxy.v1.Backend
	1, // 2: haproxy.v1.CreateBackendResponse.backend:type_name -> haproxy.v1.Backend
	1, // 3: haproxy.v1.GetBackendResponse.backend:type_name -> haproxy.v1.Backend
	1, // 4: haproxy.v1.ListBackendsResponse.backends:type_name -> haproxy.v1.Backend
	1, // 5: haproxy.v1.UpdateBackendRequest.backend:type_name -> haproxy.v1.Backend
	1, // 6: haproxy.v1.UpdateBackendResponse.backend:type_name -> haproxy.v1.Backend
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_backend_proto_init() }
func file_backend_proto_init() {
	if File_backend_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backend_proto_rawDesc), len(file_backend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_backend_proto_goTypes,
		DependencyIndexes: file_backend_proto_depIdxs,
		MessageInfos:      file_backend_proto_msgTypes,
	}.Build()
	File_backend_proto = out.File
	file_backend_proto_goTypes = nil
	file_backend_proto_depIdxs = nil
}
