// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: bind.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Bind represents a HAProxy bind configuration
type Bind struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Address       *string                `protobuf:"bytes,3,opt,name=address,proto3,oneof" json:"address,omitempty"`
	Port          *int32                 `protobuf:"varint,4,opt,name=port,proto3,oneof" json:"port,omitempty"`
	V4V6          *bool                  `protobuf:"varint,5,opt,name=v4v6,proto3,oneof" json:"v4v6,omitempty"`
	V6Only        *bool                  `protobuf:"varint,6,opt,name=v6only,proto3,oneof" json:"v6only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bind) Reset() {
	*x = Bind{}
	mi := &file_bind_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bind) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bind) ProtoMessage() {}

func (x *Bind) ProtoReflect() protoreflect.Message {
	mi := &file_bind_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bind.ProtoReflect.Descriptor instead.
func (*Bind) Descriptor() ([]byte, []int) {
	return file_bind_proto_rawDescGZIP(), []int{0}
}

func (x *Bind) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Bind) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Bind) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *Bind) GetPort() int32 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

func (x *Bind) GetV4V6() bool {
	if x != nil && x.V4V6 != nil {
		return *x.V4V6
	}
	return false
}

func (x *Bind) GetV6Only() bool {
	if x != nil && x.V6Only != nil {
		return *x.V6Only
	}
	return false
}

type CreateBindRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	FrontendName  string                 `protobuf:"bytes,2,opt,name=frontend_name,json=frontendName,proto3" json:"frontend_name,omitempty"`
	Bind          *Bind                  `protobuf:"bytes,3,opt,name=bind,proto3" json:"bind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBindRequest) Reset() {
	*x = CreateBindRequest{}
	mi := &file_bind_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBindRequest) ProtoMessage() {}

func (x *CreateBindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bind_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBindRequest.ProtoReflect.Descriptor instead.
func (*CreateBindRequest) Descriptor() ([]byte, []int) {
	return file_bind_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBindRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *CreateBindRequest) GetFrontendName() string {
	if x != nil {
		return x.FrontendName
	}
	return ""
}

func (x *CreateBindRequest) GetBind() *Bind {
	if x != nil {
		return x.Bind
	}
	return nil
}

type CreateBindResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bind          *Bind                  `protobuf:"bytes,1,opt,name=bind,proto3" json:"bind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBindResponse) Reset() {
	*x = CreateBindResponse{}
	mi := &file_bind_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBindResponse) ProtoMessage() {}

func (x *CreateBindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bind_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBindResponse.ProtoReflect.Descriptor instead.
func (*CreateBindResponse) Descriptor() ([]byte, []int) {
	return file_bind_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBindResponse) GetBind() *Bind {
	if x != nil {
		return x.Bind
	}
	return nil
}

type GetBindRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	FrontendName  string                 `protobuf:"bytes,2,opt,name=frontend_name,json=frontendName,proto3" json:"frontend_name,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBindRequest) Reset() {
	*x = GetBindRequest{}
	mi := &file_bind_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBindRequest) ProtoMessage() {}

func (x *GetBindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bind_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBindRequest.ProtoReflect.Descriptor instead.
func (*GetBindRequest) Descriptor() ([]byte, []int) {
	return file_bind_proto_rawDescGZIP(), []int{3}
}

func (x *GetBindRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *GetBindRequest) GetFrontendName() string {
	if x != nil {
		return x.FrontendName
	}
	return ""
}

func (x *GetBindRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetBindResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bind          *Bind                  `protobuf:"bytes,1,opt,name=bind,proto3" json:"bind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBindResponse) Reset() {
	*x = GetBindResponse{}
	mi := &file_bind_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBindResponse) ProtoMessage() {}

func (x *GetBindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bind_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBindResponse.ProtoReflect.Descriptor instead.
func (*GetBindResponse) Descriptor() ([]byte, []int) {
	return file_bind_proto_rawDescGZIP(), []int{4}
}

func (x *GetBindResponse) GetBind() *Bind {
	if x != nil {
		return x.Bind
	}
	return nil
}

type ListBindsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	FrontendName  string                 `protobuf:"bytes,2,opt,name=frontend_name,json=frontendName,proto3" json:"frontend_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBindsRequest) Reset() {
	*x = ListBindsRequest{}
	mi := &file_bind_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBindsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBindsRequest) ProtoMessage() {}

func (x *ListBindsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bind_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBindsRequest.ProtoReflect.Descriptor instead.
func (*ListBindsRequest) Descriptor() ([]byte, []int) {
	return file_bind_proto_rawDescGZIP(), []int{5}
}

func (x *ListBindsRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *ListBindsRequest) GetFrontendName() string {
	if x != nil {
		return x.FrontendName
	}
	return ""
}

type ListBindsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Binds         []*Bind                `protobuf:"bytes,1,rep,name=binds,proto3" json:"binds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBindsResponse) Reset() {
	*x = ListBindsResponse{}
	mi := &file_bind_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBindsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBindsResponse) ProtoMessage() {}

func (x *ListBindsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bind_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBindsResponse.ProtoReflect.Descriptor instead.
func (*ListBindsResponse) Descriptor() ([]byte, []int) {
	return file_bind_proto_rawDescGZIP(), []int{6}
}

func (x *ListBindsResponse) GetBinds() []*Bind {
	if x != nil {
		return x.Binds
	}
	return nil
}

type UpdateBindRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	FrontendName  string                 `protobuf:"bytes,2,opt,name=frontend_name,json=frontendName,proto3" json:"frontend_name,omitempty"`
	Bind          *Bind                  `protobuf:"bytes,3,opt,name=bind,proto3" json:"bind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBindRequest) Reset() {
	*x = UpdateBindRequest{}
	mi := &file_bind_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBindRequest) ProtoMessage() {}

func (x *UpdateBindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bind_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBindRequest.ProtoReflect.Descriptor instead.
func (*UpdateBindRequest) Descriptor() ([]byte, []int) {
	return file_bind_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateBindRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *UpdateBindRequest) GetFrontendName() string {
	if x != nil {
		return x.FrontendName
	}
	return ""
}

func (x *UpdateBindRequest) GetBind() *Bind {
	if x != nil {
		return x.Bind
	}
	return nil
}

type UpdateBindResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bind          *Bind                  `protobuf:"bytes,1,opt,name=bind,proto3" json:"bind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBindResponse) Reset() {
	*x = UpdateBindResponse{}
	mi := &file_bind_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBindResponse) ProtoMessage() {}

func (x *UpdateBindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bind_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBindResponse.ProtoReflect.Descriptor instead.
func (*UpdateBindResponse) Descriptor() ([]byte, []int) {
	return file_bind_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateBindResponse) GetBind() *Bind {
	if x != nil {
		return x.Bind
	}
	return nil
}

type DeleteBindRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	FrontendName  string                 `protobuf:"bytes,2,opt,name=frontend_name,json=frontendName,proto3" json:"frontend_name,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBindRequest) Reset() {
	*x = DeleteBindRequest{}
	mi := &file_bind_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBindRequest) ProtoMessage() {}

func (x *DeleteBindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bind_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBindRequest.ProtoReflect.Descriptor instead.
func (*DeleteBindRequest) Descriptor() ([]byte, []int) {
	return file_bind_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteBindRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *DeleteBindRequest) GetFrontendName() string {
	if x != nil {
		return x.FrontendName
	}
	return ""
}

func (x *DeleteBindRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteBindResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBindResponse) Reset() {
	*x = DeleteBindResponse{}
	mi := &file_bind_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBindResponse) ProtoMessage() {}

func (x *DeleteBindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bind_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBindResponse.ProtoReflect.Descriptor instead.
func (*DeleteBindResponse) Descriptor() ([]byte, []int) {
	return file_bind_proto_rawDescGZIP(), []int{10}
}

var File_bind_proto protoreflect.FileDescriptor

const file_bind_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"bind.proto\x12\n" +
	"haproxy.v1\"\xdb\x01\n" +
	"\x04Bind\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x01R\x04name\x88\x01\x01\x12\x1d\n" +
	"\aaddress\x18\x03 \x01(\tH\x02R\aaddress\x88\x01\x01\x12\x17\n" +
	"\x04port\x18\x04 \x01(\x05H\x03R\x04port\x88\x01\x01\x12\x17\n" +
	"\x04v4v6\x18\x05 \x01(\bH\x04R\x04v4v6\x88\x01\x01\x12\x1b\n" +
	"\x06v6only\x18\x06 \x01(\bH\x05R\x06v6only\x88\x01\x01B\x05\n" +
	"\x03_idB\a\n" +
	"\x05_nameB\n" +
	"\n" +
	"\b_addressB\a\n" +
	"\x05_portB\a\n" +
	"\x05_v4v6B\t\n" +
	"\a_v6only\"\x85\x01\n" +
	"\x11CreateBindRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12#\n" +
	"\rfrontend_name\x18\x02 \x01(\tR\ffrontendName\x12$\n" +
	"\x04bind\x18\x03 \x01(\v2\x10.haproxy.v1.BindR\x04bind\":\n" +
	"\x12CreateBindResponse\x12$\n" +
	"\x04bind\x18\x01 \x01(\v2\x10.haproxy.v1.BindR\x04bind\"p\n" +
	"\x0eGetBindRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12#\n" +
	"\rfrontend_name\x18\x02 \x01(\tR\ffrontendName\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"7\n" +
	"\x0fGetBindResponse\x12$\n" +
	"\x04bind\x18\x01 \x01(\v2\x10.haproxy.v1.BindR\x04bind\"^\n" +
	"\x10ListBindsRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12#\n" +
	"\rfrontend_name\x18\x02 \x01(\tR\ffrontendName\";\n" +
	"\x11ListBindsResponse\x12&\n" +
	"\x05binds\x18\x01 \x03(\v2\x10.haproxy.v1.BindR\x05binds\"\x85\x01\n" +
	"\x11UpdateBindRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12#\n" +
	"\rfrontend_name\x18\x02 \x01(\tR\ffrontendName\x12$\n" +
	"\x04bind\x18\x03 \x01(\v2\x10.haproxy.v1.BindR\x04bind\":\n" +
	"\x12UpdateBindResponse\x12$\n" +
	"\x04bind\x18\x01 \x01(\v2\x10.haproxy.v1.BindR\x04bind\"s\n" +
	"\x11DeleteBindRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12#\n" +
	"\rfrontend_name\x18\x02 \x01(\tR\ffrontendName\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\x14\n" +
	"\x12DeleteBindResponseB<Z:github.com/bear-san/haproxy-network-manager/pkg/haproxy/v1b\x06proto3"

var (
	file_bind_proto_rawDescOnce sync.Once
	file_bind_proto_rawDescData []byte
)

func file_bind_proto_rawDescGZIP() []byte {
	file_bind_proto_rawDescOnce.Do(func() {
		file_bind_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bind_proto_rawDesc), len(file_bind_proto_rawDesc)))
	})
	return file_bind_proto_rawDescData
}

var file_bind_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_bind_proto_goTypes = []any{
	(*Bind)(nil),               // 0: haproxy.v1.Bind
	(*CreateBindRequest)(nil),  // 1: haproxy.v1.CreateBindRequest
	(*CreateBindResponse)(nil), // 2: haproxy.v1.CreateBindResponse
	(*GetBindRequest)(nil),     // 3: haproxy.v1.GetBindRequest
	(*GetBindResponse)(nil),    // 4: haproxy.v1.GetBindResponse
	(*ListBindsRequest)(nil),   // 5: haproxy.v1.ListBindsRequest
	(*ListBindsResponse)(nil),  // 6: haproxy.v1.ListBindsResponse
	(*UpdateBindRequest)(nil),  // 7: haproxy.v1.UpdateBindRequest
	(*UpdateBindResponse)(nil), // 8: haproxy.v1.UpdateBindResponse
	(*DeleteBindRequest)(nil),  // 9: haproxy.v1.DeleteBindRequest
	(*DeleteBindResponse)(nil), // 10: haproxy.v1.DeleteBindResponse
}
var file_bind_proto_depIdxs = []int32{
	0, // 0: haproxy.v1.CreateBindRequest.bind:type_name -> haproxy.v1.Bind
	0, // 1: haproxy.v1.CreateBindResponse.bind:type_name -> haproxy.v1.Bind
	0, // 2: haproxy.v1.GetBindResponse.bind:type_name -> haproxy.v1.Bind
	0, // 3: haproxy.v1.ListBindsResponse.binds:type_name -> haproxy.v1.Bind
	0, // 4: haproxy.v1.UpdateBindRequest.bind:type_name -> haproxy.v1.Bind
	0, // 5: haproxy.v1.UpdateBindResponse.bind:type_name -> haproxy.v1.Bind
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_bind_proto_init() }
func file_bind_proto_init() {
	if File_bind_proto != nil {
		return
	}
	file_bind_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bind_proto_rawDesc), len(file_bind_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bind_proto_goTypes,
		DependencyIndexes: file_bind_proto_depIdxs,
		MessageInfos:      file_bind_proto_msgTypes,
	}.Build()
	File_bind_proto = out.File
	file_bind_proto_goTypes = nil
	file_bind_proto_depIdxs = nil
}
