// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: frontend.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Frontend represents a HAProxy frontend configuration
type Frontend struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DefaultBackend string                 `protobuf:"bytes,1,opt,name=default_backend,json=defaultBackend,proto3" json:"default_backend,omitempty"`
	Description    string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Disabled       bool                   `protobuf:"varint,3,opt,name=disabled,proto3" json:"disabled,omitempty"`
	Enabled        bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Id             int32                  `protobuf:"varint,5,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Mode           ProxyMode              `protobuf:"varint,7,opt,name=mode,proto3,enum=haproxy.v1.ProxyMode" json:"mode,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Frontend) Reset() {
	*x = Frontend{}
	mi := &file_frontend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frontend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frontend) ProtoMessage() {}

func (x *Frontend) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frontend.ProtoReflect.Descriptor instead.
func (*Frontend) Descriptor() ([]byte, []int) {
	return file_frontend_proto_rawDescGZIP(), []int{0}
}

func (x *Frontend) GetDefaultBackend() string {
	if x != nil {
		return x.DefaultBackend
	}
	return ""
}

func (x *Frontend) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Frontend) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *Frontend) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Frontend) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Frontend) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Frontend) GetMode() ProxyMode {
	if x != nil {
		return x.Mode
	}
	return ProxyMode_PROXY_MODE_UNSPECIFIED
}

type CreateFrontendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Frontend      *Frontend              `protobuf:"bytes,2,opt,name=frontend,proto3" json:"frontend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFrontendRequest) Reset() {
	*x = CreateFrontendRequest{}
	mi := &file_frontend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFrontendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFrontendRequest) ProtoMessage() {}

func (x *CreateFrontendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFrontendRequest.ProtoReflect.Descriptor instead.
func (*CreateFrontendRequest) Descriptor() ([]byte, []int) {
	return file_frontend_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFrontendRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *CreateFrontendRequest) GetFrontend() *Frontend {
	if x != nil {
		return x.Frontend
	}
	return nil
}

type CreateFrontendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frontend      *Frontend              `protobuf:"bytes,1,opt,name=frontend,proto3" json:"frontend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFrontendResponse) Reset() {
	*x = CreateFrontendResponse{}
	mi := &file_frontend_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFrontendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFrontendResponse) ProtoMessage() {}

func (x *CreateFrontendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFrontendResponse.ProtoReflect.Descriptor instead.
func (*CreateFrontendResponse) Descriptor() ([]byte, []int) {
	return file_frontend_proto_rawDescGZIP(), []int{2}
}

func (x *CreateFrontendResponse) GetFrontend() *Frontend {
	if x != nil {
		return x.Frontend
	}
	return nil
}

type GetFrontendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFrontendRequest) Reset() {
	*x = GetFrontendRequest{}
	mi := &file_frontend_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFrontendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFrontendRequest) ProtoMessage() {}

func (x *GetFrontendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFrontendRequest.ProtoReflect.Descriptor instead.
func (*GetFrontendRequest) Descriptor() ([]byte, []int) {
	return file_frontend_proto_rawDescGZIP(), []int{3}
}

func (x *GetFrontendRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *GetFrontendRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetFrontendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frontend      *Frontend              `protobuf:"bytes,1,opt,name=frontend,proto3" json:"frontend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFrontendResponse) Reset() {
	*x = GetFrontendResponse{}
	mi := &file_frontend_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFrontendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFrontendResponse) ProtoMessage() {}

func (x *GetFrontendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFrontendResponse.ProtoReflect.Descriptor instead.
func (*GetFrontendResponse) Descriptor() ([]byte, []int) {
	return file_frontend_proto_rawDescGZIP(), []int{4}
}

func (x *GetFrontendResponse) GetFrontend() *Frontend {
	if x != nil {
		return x.Frontend
	}
	return nil
}

type ListFrontendsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFrontendsRequest) Reset() {
	*x = ListFrontendsRequest{}
	mi := &file_frontend_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFrontendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFrontendsRequest) ProtoMessage() {}

func (x *ListFrontendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFrontendsRequest.ProtoReflect.Descriptor instead.
func (*ListFrontendsRequest) Descriptor() ([]byte, []int) {
	return file_frontend_proto_rawDescGZIP(), []int{5}
}

func (x *ListFrontendsRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type ListFrontendsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frontends     []*Frontend            `protobuf:"bytes,1,rep,name=frontends,proto3" json:"frontends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFrontendsResponse) Reset() {
	*x = ListFrontendsResponse{}
	mi := &file_frontend_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFrontendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFrontendsResponse) ProtoMessage() {}

func (x *ListFrontendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFrontendsResponse.ProtoReflect.Descriptor instead.
func (*ListFrontendsResponse) Descriptor() ([]byte, []int) {
	return file_frontend_proto_rawDescGZIP(), []int{6}
}

func (x *ListFrontendsResponse) GetFrontends() []*Frontend {
	if x != nil {
		return x.Frontends
	}
	return nil
}

type UpdateFrontendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Frontend      *Frontend              `protobuf:"bytes,3,opt,name=frontend,proto3" json:"frontend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFrontendRequest) Reset() {
	*x = UpdateFrontendRequest{}
	mi := &file_frontend_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFrontendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFrontendRequest) ProtoMessage() {}

func (x *UpdateFrontendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFrontendRequest.ProtoReflect.Descriptor instead.
func (*UpdateFrontendRequest) Descriptor() ([]byte, []int) {
	return file_frontend_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateFrontendRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *UpdateFrontendRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateFrontendRequest) GetFrontend() *Frontend {
	if x != nil {
		return x.Frontend
	}
	return nil
}

type UpdateFrontendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frontend      *Frontend              `protobuf:"bytes,1,opt,name=frontend,proto3" json:"frontend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFrontendResponse) Reset() {
	*x = UpdateFrontendResponse{}
	mi := &file_frontend_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFrontendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFrontendResponse) ProtoMessage() {}

func (x *UpdateFrontendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFrontendResponse.ProtoReflect.Descriptor instead.
func (*UpdateFrontendResponse) Descriptor() ([]byte, []int) {
	return file_frontend_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateFrontendResponse) GetFrontend() *Frontend {
	if x != nil {
		return x.Frontend
	}
	return nil
}

type DeleteFrontendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFrontendRequest) Reset() {
	*x = DeleteFrontendRequest{}
	mi := &file_frontend_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFrontendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFrontendRequest) ProtoMessage() {}

func (x *DeleteFrontendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFrontendRequest.ProtoReflect.Descriptor instead.
func (*DeleteFrontendRequest) Descriptor() ([]byte, []int) {
	return file_frontend_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteFrontendRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *DeleteFrontendRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteFrontendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFrontendResponse) Reset() {
	*x = DeleteFrontendResponse{}
	mi := &file_frontend_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFrontendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFrontendResponse) ProtoMessage() {}

func (x *DeleteFrontendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFrontendResponse.ProtoReflect.Descriptor instead.
func (*DeleteFrontendResponse) Descriptor() ([]byte, []int) {
	return file_frontend_proto_rawDescGZIP(), []int{10}
}

var File_frontend_proto protoreflect.FileDescriptor

const file_frontend_proto_rawDesc = "" +
	"\n" +
	"\x0efrontend.proto\x12\n" +
	"haproxy.v1\x1a\fcommon.proto\"\xda\x01\n" +
	"\bFrontend\x12'\n" +
	"\x0fdefault_backend\x18\x01 \x01(\tR\x0edefaultBackend\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bdisabled\x18\x03 \x01(\bR\bdisabled\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12\x0e\n" +
	"\x02id\x18\x05 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12)\n" +
	"\x04mode\x18\a \x01(\x0e2\x15.haproxy.v1.ProxyModeR\x04mode\"p\n" +
	"\x15CreateFrontendRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x120\n" +
	"\bfrontend\x18\x02 \x01(\v2\x14.haproxy.v1.FrontendR\bfrontend\"J\n" +
	"\x16CreateFrontendResponse\x120\n" +
	"\bfrontend\x18\x01 \x01(\v2\x14.haproxy.v1.FrontendR\bfrontend\"O\n" +
	"\x12GetFrontendRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"G\n" +
	"\x13GetFrontendResponse\x120\n" +
	"\bfrontend\x18\x01 \x01(\v2\x14.haproxy.v1.FrontendR\bfrontend\"=\n" +
	"\x14ListFrontendsRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\"K\n" +
	"\x15ListFrontendsResponse\x122\n" +
	"\tfrontends\x18\x01 \x03(\v2\x14.haproxy.v1.FrontendR\tfrontends\"\x84\x01\n" +
	"\x15UpdateFrontendRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x120\n" +
	"\bfrontend\x18\x03 \x01(\v2\x14.haproxy.v1.FrontendR\bfrontend\"J\n" +
	"\x16UpdateFrontendResponse\x120\n" +
	"\bfrontend\x18\x01 \x01(\v2\x14.haproxy.v1.FrontendR\bfrontend\"R\n" +
	"\x15DeleteFrontendRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x18\n" +
	"\x16DeleteFrontendResponseB9Z7github.com/bear-san/haproxy-configurator/pkg/haproxy/v1b\x06proto3"

var (
	file_frontend_proto_rawDescOnce sync.Once
	file_frontend_proto_rawDescData []byte
)

func file_frontend_proto_rawDescGZIP() []byte {
	file_frontend_proto_rawDescOnce.Do(func() {
		file_frontend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_frontend_proto_rawDesc), len(file_frontend_proto_rawDesc)))
	})
	return file_frontend_proto_rawDescData
}

var file_frontend_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_frontend_proto_goTypes = []any{
	(*Frontend)(nil),               // 0: haproxy.v1.Frontend
	(*CreateFrontendRequest)(nil),  // 1: haproxy.v1.CreateFrontendRequest
	(*CreateFrontendResponse)(nil), // 2: haproxy.v1.CreateFrontendResponse
	(*GetFrontendRequest)(nil),     // 3: haproxy.v1.GetFrontendRequest
	(*GetFrontendResponse)(nil),    // 4: haproxy.v1.GetFrontendResponse
	(*ListFrontendsRequest)(nil),   // 5: haproxy.v1.ListFrontendsRequest
	(*ListFrontendsResponse)(nil),  // 6: haproxy.v1.ListFrontendsResponse
	(*UpdateFrontendRequest)(nil),  // 7: haproxy.v1.UpdateFrontendRequest
	(*UpdateFrontendResponse)(nil), // 8: haproxy.v1.UpdateFrontendResponse
	(*DeleteFrontendRequest)(nil),  // 9: haproxy.v1.DeleteFrontendRequest
	(*DeleteFrontendResponse)(nil), // 10: haproxy.v1.DeleteFrontendResponse
	(ProxyMode)(0),                 // 11: haproxy.v1.ProxyMode
}
var file_frontend_proto_depIdxs = []int32{
	11, // 0: haproxy.v1.Frontend.mode:type_name -> haproxy.v1.ProxyMode
	0,  // 1: haproxy.v1.CreateFrontendRequest.frontend:type_name -> haproxy.v1.Frontend
	0,  // 2: haproxy.v1.CreateFrontendResponse.frontend:type_name -> haproxy.v1.Frontend
	0,  // 3: haproxy.v1.GetFrontendResponse.frontend:type_name -> haproxy.v1.Frontend
	0,  // 4: haproxy.v1.ListFrontendsResponse.frontends:type_name -> haproxy.v1.Frontend
	0,  // 5: haproxy.v1.UpdateFrontendRequest.frontend:type_name -> haproxy.v1.Frontend
	0,  // 6: haproxy.v1.UpdateFrontendResponse.frontend:type_name -> haproxy.v1.Frontend
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_frontend_proto_init() }
func file_frontend_proto_init() {
	if File_frontend_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_frontend_proto_rawDesc), len(file_frontend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_frontend_proto_goTypes,
		DependencyIndexes: file_frontend_proto_depIdxs,
		MessageInfos:      file_frontend_proto_msgTypes,
	}.Build()
	File_frontend_proto = out.File
	file_frontend_proto_goTypes = nil
	file_frontend_proto_depIdxs = nil
}
