// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: frontend.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FrontendService_CreateFrontend_FullMethodName = "/haproxy.v1.FrontendService/CreateFrontend"
	FrontendService_GetFrontend_FullMethodName    = "/haproxy.v1.FrontendService/GetFrontend"
	FrontendService_ListFrontends_FullMethodName  = "/haproxy.v1.FrontendService/ListFrontends"
	FrontendService_UpdateFrontend_FullMethodName = "/haproxy.v1.FrontendService/UpdateFrontend"
	FrontendService_DeleteFrontend_FullMethodName = "/haproxy.v1.FrontendService/DeleteFrontend"
)

// FrontendServiceClient is the client API for FrontendService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FrontendService provides CRUD operations for HAProxy frontend configuration
type FrontendServiceClient interface {
	CreateFrontend(ctx context.Context, in *CreateFrontendRequest, opts ...grpc.CallOption) (*CreateFrontendResponse, error)
	GetFrontend(ctx context.Context, in *GetFrontendRequest, opts ...grpc.CallOption) (*GetFrontendResponse, error)
	ListFrontends(ctx context.Context, in *ListFrontendsRequest, opts ...grpc.CallOption) (*ListFrontendsResponse, error)
	UpdateFrontend(ctx context.Context, in *UpdateFrontendRequest, opts ...grpc.CallOption) (*UpdateFrontendResponse, error)
	DeleteFrontend(ctx context.Context, in *DeleteFrontendRequest, opts ...grpc.CallOption) (*DeleteFrontendResponse, error)
}

type frontendServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFrontendServiceClient(cc grpc.ClientConnInterface) FrontendServiceClient {
	return &frontendServiceClient{cc}
}

func (c *frontendServiceClient) CreateFrontend(ctx context.Context, in *CreateFrontendRequest, opts ...grpc.CallOption) (*CreateFrontendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFrontendResponse)
	err := c.cc.Invoke(ctx, FrontendService_CreateFrontend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontendServiceClient) GetFrontend(ctx context.Context, in *GetFrontendRequest, opts ...grpc.CallOption) (*GetFrontendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFrontendResponse)
	err := c.cc.Invoke(ctx, FrontendService_GetFrontend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontendServiceClient) ListFrontends(ctx context.Context, in *ListFrontendsRequest, opts ...grpc.CallOption) (*ListFrontendsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFrontendsResponse)
	err := c.cc.Invoke(ctx, FrontendService_ListFrontends_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontendServiceClient) UpdateFrontend(ctx context.Context, in *UpdateFrontendRequest, opts ...grpc.CallOption) (*UpdateFrontendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateFrontendResponse)
	err := c.cc.Invoke(ctx, FrontendService_UpdateFrontend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontendServiceClient) DeleteFrontend(ctx context.Context, in *DeleteFrontendRequest, opts ...grpc.CallOption) (*DeleteFrontendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFrontendResponse)
	err := c.cc.Invoke(ctx, FrontendService_DeleteFrontend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FrontendServiceServer is the server API for FrontendService service.
// All implementations must embed UnimplementedFrontendServiceServer
// for forward compatibility.
//
// FrontendService provides CRUD operations for HAProxy frontend configuration
type FrontendServiceServer interface {
	CreateFrontend(context.Context, *CreateFrontendRequest) (*CreateFrontendResponse, error)
	GetFrontend(context.Context, *GetFrontendRequest) (*GetFrontendResponse, error)
	ListFrontends(context.Context, *ListFrontendsRequest) (*ListFrontendsResponse, error)
	UpdateFrontend(context.Context, *UpdateFrontendRequest) (*UpdateFrontendResponse, error)
	DeleteFrontend(context.Context, *DeleteFrontendRequest) (*DeleteFrontendResponse, error)
	mustEmbedUnimplementedFrontendServiceServer()
}

// UnimplementedFrontendServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFrontendServiceServer struct{}

func (UnimplementedFrontendServiceServer) CreateFrontend(context.Context, *CreateFrontendRequest) (*CreateFrontendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFrontend not implemented")
}
func (UnimplementedFrontendServiceServer) GetFrontend(context.Context, *GetFrontendRequest) (*GetFrontendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFrontend not implemented")
}
func (UnimplementedFrontendServiceServer) ListFrontends(context.Context, *ListFrontendsRequest) (*ListFrontendsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFrontends not implemented")
}
func (UnimplementedFrontendServiceServer) UpdateFrontend(context.Context, *UpdateFrontendRequest) (*UpdateFrontendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFrontend not implemented")
}
func (UnimplementedFrontendServiceServer) DeleteFrontend(context.Context, *DeleteFrontendRequest) (*DeleteFrontendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFrontend not implemented")
}
func (UnimplementedFrontendServiceServer) mustEmbedUnimplementedFrontendServiceServer() {}
func (UnimplementedFrontendServiceServer) testEmbeddedByValue()                         {}

// UnsafeFrontendServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FrontendServiceServer will
// result in compilation errors.
type UnsafeFrontendServiceServer interface {
	mustEmbedUnimplementedFrontendServiceServer()
}

func RegisterFrontendServiceServer(s grpc.ServiceRegistrar, srv FrontendServiceServer) {
	// If the following call pancis, it indicates UnimplementedFrontendServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FrontendService_ServiceDesc, srv)
}

func _FrontendService_CreateFrontend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFrontendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontendServiceServer).CreateFrontend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FrontendService_CreateFrontend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontendServiceServer).CreateFrontend(ctx, req.(*CreateFrontendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FrontendService_GetFrontend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFrontendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontendServiceServer).GetFrontend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FrontendService_GetFrontend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontendServiceServer).GetFrontend(ctx, req.(*GetFrontendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FrontendService_ListFrontends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFrontendsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontendServiceServer).ListFrontends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FrontendService_ListFrontends_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontendServiceServer).ListFrontends(ctx, req.(*ListFrontendsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FrontendService_UpdateFrontend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFrontendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontendServiceServer).UpdateFrontend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FrontendService_UpdateFrontend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontendServiceServer).UpdateFrontend(ctx, req.(*UpdateFrontendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FrontendService_DeleteFrontend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFrontendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontendServiceServer).DeleteFrontend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FrontendService_DeleteFrontend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontendServiceServer).DeleteFrontend(ctx, req.(*DeleteFrontendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FrontendService_ServiceDesc is the grpc.ServiceDesc for FrontendService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FrontendService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "haproxy.v1.FrontendService",
	HandlerType: (*FrontendServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFrontend",
			Handler:    _FrontendService_CreateFrontend_Handler,
		},
		{
			MethodName: "GetFrontend",
			Handler:    _FrontendService_GetFrontend_Handler,
		},
		{
			MethodName: "ListFrontends",
			Handler:    _FrontendService_ListFrontends_Handler,
		},
		{
			MethodName: "UpdateFrontend",
			Handler:    _FrontendService_UpdateFrontend_Handler,
		},
		{
			MethodName: "DeleteFrontend",
			Handler:    _FrontendService_DeleteFrontend_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "frontend.proto",
}
