// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: haproxy.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_haproxy_proto protoreflect.FileDescriptor

const file_haproxy_proto_rawDesc = "" +
	"\n" +
	"\rhaproxy.proto\x12\n" +
	"haproxy.v1\x1a\x11transaction.proto\x1a\rbackend.proto\x1a\x0efrontend.proto\x1a\n" +
	"bind.proto\x1a\fserver.proto2\xbb\x10\n" +
	"\x15HAProxyManagerService\x12K\n" +
	"\n" +
	"GetVersion\x12\x1d.haproxy.v1.GetVersionRequest\x1a\x1e.haproxy.v1.GetVersionResponse\x12`\n" +
	"\x11CreateTransaction\x12$.haproxy.v1.CreateTransactionRequest\x1a%.haproxy.v1.CreateTransactionResponse\x12W\n" +
	"\x0eGetTransaction\x12!.haproxy.v1.GetTransactionRequest\x1a\".haproxy.v1.GetTransactionResponse\x12`\n" +
	"\x11CommitTransaction\x12$.haproxy.v1.CommitTransactionRequest\x1a%.haproxy.v1.CommitTransactionResponse\x12]\n" +
	"\x10CloseTransaction\x12#.haproxy.v1.CloseTransactionRequest\x1a$.haproxy.v1.CloseTransactionResponse\x12T\n" +
	"\rCreateBackend\x12 .haproxy.v1.CreateBackendRequest\x1a!.haproxy.v1.CreateBackendResponse\x12K\n" +
	"\n" +
	"GetBackend\x12\x1d.haproxy.v1.GetBackendRequest\x1a\x1e.haproxy.v1.GetBackendResponse\x12Q\n" +
	"\fListBackends\x12\x1f.haproxy.v1.ListBackendsRequest\x1a .haproxy.v1.ListBackendsResponse\x12T\n" +
	"\rUpdateBackend\x12 .haproxy.v1.UpdateBackendRequest\x1a!.haproxy.v1.UpdateBackendResponse\x12T\n" +
	"\rDeleteBackend\x12 .haproxy.v1.DeleteBackendRequest\x1a!.haproxy.v1.DeleteBackendResponse\x12W\n" +
	"\x0eCreateFrontend\x12!.haproxy.v1.CreateFrontendRequest\x1a\".haproxy.v1.CreateFrontendResponse\x12N\n" +
	"\vGetFrontend\x12\x1e.haproxy.v1.GetFrontendRequest\x1a\x1f.haproxy.v1.GetFrontendResponse\x12T\n" +
	"\rListFrontends\x12 .haproxy.v1.ListFrontendsRequest\x1a!.haproxy.v1.ListFrontendsResponse\x12W\n" +
	"\x0eUpdateFrontend\x12!.haproxy.v1.UpdateFrontendRequest\x1a\".haproxy.v1.UpdateFrontendResponse\x12W\n" +
	"\x0eDeleteFrontend\x12!.haproxy.v1.DeleteFrontendRequest\x1a\".haproxy.v1.DeleteFrontendResponse\x12K\n" +
	"\n" +
	"CreateBind\x12\x1d.haproxy.v1.CreateBindRequest\x1a\x1e.haproxy.v1.CreateBindResponse\x12B\n" +
	"\aGetBind\x12\x1a.haproxy.v1.GetBindRequest\x1a\x1b.haproxy.v1.GetBindResponse\x12H\n" +
	"\tListBinds\x12\x1c.haproxy.v1.ListBindsRequest\x1a\x1d.haproxy.v1.ListBindsResponse\x12K\n" +
	"\n" +
	"UpdateBind\x12\x1d.haproxy.v1.UpdateBindRequest\x1a\x1e.haproxy.v1.UpdateBindResponse\x12K\n" +
	"\n" +
	"DeleteBind\x12\x1d.haproxy.v1.DeleteBindRequest\x1a\x1e.haproxy.v1.DeleteBindResponse\x12Q\n" +
	"\fCreateServer\x12\x1f.haproxy.v1.CreateServerRequest\x1a .haproxy.v1.CreateServerResponse\x12H\n" +
	"\tGetServer\x12\x1c.haproxy.v1.GetServerRequest\x1a\x1d.haproxy.v1.GetServerResponse\x12N\n" +
	"\vListServers\x12\x1e.haproxy.v1.ListServersRequest\x1a\x1f.haproxy.v1.ListServersResponse\x12Q\n" +
	"\fUpdateServer\x12\x1f.haproxy.v1.UpdateServerRequest\x1a .haproxy.v1.UpdateServerResponse\x12Q\n" +
	"\fDeleteServer\x12\x1f.haproxy.v1.DeleteServerRequest\x1a .haproxy.v1.DeleteServerResponseB<Z:github.com/bear-san/haproxy-network-manager/pkg/haproxy/v1b\x06proto3"

var file_haproxy_proto_goTypes = []any{
	(*GetVersionRequest)(nil),         // 0: haproxy.v1.GetVersionRequest
	(*CreateTransactionRequest)(nil),  // 1: haproxy.v1.CreateTransactionRequest
	(*GetTransactionRequest)(nil),     // 2: haproxy.v1.GetTransactionRequest
	(*CommitTransactionRequest)(nil),  // 3: haproxy.v1.CommitTransactionRequest
	(*CloseTransactionRequest)(nil),   // 4: haproxy.v1.CloseTransactionRequest
	(*CreateBackendRequest)(nil),      // 5: haproxy.v1.CreateBackendRequest
	(*GetBackendRequest)(nil),         // 6: haproxy.v1.GetBackendRequest
	(*ListBackendsRequest)(nil),       // 7: haproxy.v1.ListBackendsRequest
	(*UpdateBackendRequest)(nil),      // 8: haproxy.v1.UpdateBackendRequest
	(*DeleteBackendRequest)(nil),      // 9: haproxy.v1.DeleteBackendRequest
	(*CreateFrontendRequest)(nil),     // 10: haproxy.v1.CreateFrontendRequest
	(*GetFrontendRequest)(nil),        // 11: haproxy.v1.GetFrontendRequest
	(*ListFrontendsRequest)(nil),      // 12: haproxy.v1.ListFrontendsRequest
	(*UpdateFrontendRequest)(nil),     // 13: haproxy.v1.UpdateFrontendRequest
	(*DeleteFrontendRequest)(nil),     // 14: haproxy.v1.DeleteFrontendRequest
	(*CreateBindRequest)(nil),         // 15: haproxy.v1.CreateBindRequest
	(*GetBindRequest)(nil),            // 16: haproxy.v1.GetBindRequest
	(*ListBindsRequest)(nil),          // 17: haproxy.v1.ListBindsRequest
	(*UpdateBindRequest)(nil),         // 18: haproxy.v1.UpdateBindRequest
	(*DeleteBindRequest)(nil),         // 19: haproxy.v1.DeleteBindRequest
	(*CreateServerRequest)(nil),       // 20: haproxy.v1.CreateServerRequest
	(*GetServerRequest)(nil),          // 21: haproxy.v1.GetServerRequest
	(*ListServersRequest)(nil),        // 22: haproxy.v1.ListServersRequest
	(*UpdateServerRequest)(nil),       // 23: haproxy.v1.UpdateServerRequest
	(*DeleteServerRequest)(nil),       // 24: haproxy.v1.DeleteServerRequest
	(*GetVersionResponse)(nil),        // 25: haproxy.v1.GetVersionResponse
	(*CreateTransactionResponse)(nil), // 26: haproxy.v1.CreateTransactionResponse
	(*GetTransactionResponse)(nil),    // 27: haproxy.v1.GetTransactionResponse
	(*CommitTransactionResponse)(nil), // 28: haproxy.v1.CommitTransactionResponse
	(*CloseTransactionResponse)(nil),  // 29: haproxy.v1.CloseTransactionResponse
	(*CreateBackendResponse)(nil),     // 30: haproxy.v1.CreateBackendResponse
	(*GetBackendResponse)(nil),        // 31: haproxy.v1.GetBackendResponse
	(*ListBackendsResponse)(nil),      // 32: haproxy.v1.ListBackendsResponse
	(*UpdateBackendResponse)(nil),     // 33: haproxy.v1.UpdateBackendResponse
	(*DeleteBackendResponse)(nil),     // 34: haproxy.v1.DeleteBackendResponse
	(*CreateFrontendResponse)(nil),    // 35: haproxy.v1.CreateFrontendResponse
	(*GetFrontendResponse)(nil),       // 36: haproxy.v1.GetFrontendResponse
	(*ListFrontendsResponse)(nil),     // 37: haproxy.v1.ListFrontendsResponse
	(*UpdateFrontendResponse)(nil),    // 38: haproxy.v1.UpdateFrontendResponse
	(*DeleteFrontendResponse)(nil),    // 39: haproxy.v1.DeleteFrontendResponse
	(*CreateBindResponse)(nil),        // 40: haproxy.v1.CreateBindResponse
	(*GetBindResponse)(nil),           // 41: haproxy.v1.GetBindResponse
	(*ListBindsResponse)(nil),         // 42: haproxy.v1.ListBindsResponse
	(*UpdateBindResponse)(nil),        // 43: haproxy.v1.UpdateBindResponse
	(*DeleteBindResponse)(nil),        // 44: haproxy.v1.DeleteBindResponse
	(*CreateServerResponse)(nil),      // 45: haproxy.v1.CreateServerResponse
	(*GetServerResponse)(nil),         // 46: haproxy.v1.GetServerResponse
	(*ListServersResponse)(nil),       // 47: haproxy.v1.ListServersResponse
	(*UpdateServerResponse)(nil),      // 48: haproxy.v1.UpdateServerResponse
	(*DeleteServerResponse)(nil),      // 49: haproxy.v1.DeleteServerResponse
}
var file_haproxy_proto_depIdxs = []int32{
	0,  // 0: haproxy.v1.HAProxyManagerService.GetVersion:input_type -> haproxy.v1.GetVersionRequest
	1,  // 1: haproxy.v1.HAProxyManagerService.CreateTransaction:input_type -> haproxy.v1.CreateTransactionRequest
	2,  // 2: haproxy.v1.HAProxyManagerService.GetTransaction:input_type -> haproxy.v1.GetTransactionRequest
	3,  // 3: haproxy.v1.HAProxyManagerService.CommitTransaction:input_type -> haproxy.v1.CommitTransactionRequest
	4,  // 4: haproxy.v1.HAProxyManagerService.CloseTransaction:input_type -> haproxy.v1.CloseTransactionRequest
	5,  // 5: haproxy.v1.HAProxyManagerService.CreateBackend:input_type -> haproxy.v1.CreateBackendRequest
	6,  // 6: haproxy.v1.HAProxyManagerService.GetBackend:input_type -> haproxy.v1.GetBackendRequest
	7,  // 7: haproxy.v1.HAProxyManagerService.ListBackends:input_type -> haproxy.v1.ListBackendsRequest
	8,  // 8: haproxy.v1.HAProxyManagerService.UpdateBackend:input_type -> haproxy.v1.UpdateBackendRequest
	9,  // 9: haproxy.v1.HAProxyManagerService.DeleteBackend:input_type -> haproxy.v1.DeleteBackendRequest
	10, // 10: haproxy.v1.HAProxyManagerService.CreateFrontend:input_type -> haproxy.v1.CreateFrontendRequest
	11, // 11: haproxy.v1.HAProxyManagerService.GetFrontend:input_type -> haproxy.v1.GetFrontendRequest
	12, // 12: haproxy.v1.HAProxyManagerService.ListFrontends:input_type -> haproxy.v1.ListFrontendsRequest
	13, // 13: haproxy.v1.HAProxyManagerService.UpdateFrontend:input_type -> haproxy.v1.UpdateFrontendRequest
	14, // 14: haproxy.v1.HAProxyManagerService.DeleteFrontend:input_type -> haproxy.v1.DeleteFrontendRequest
	15, // 15: haproxy.v1.HAProxyManagerService.CreateBind:input_type -> haproxy.v1.CreateBindRequest
	16, // 16: haproxy.v1.HAProxyManagerService.GetBind:input_type -> haproxy.v1.GetBindRequest
	17, // 17: haproxy.v1.HAProxyManagerService.ListBinds:input_type -> haproxy.v1.ListBindsRequest
	18, // 18: haproxy.v1.HAProxyManagerService.UpdateBind:input_type -> haproxy.v1.UpdateBindRequest
	19, // 19: haproxy.v1.HAProxyManagerService.DeleteBind:input_type -> haproxy.v1.DeleteBindRequest
	20, // 20: haproxy.v1.HAProxyManagerService.CreateServer:input_type -> haproxy.v1.CreateServerRequest
	21, // 21: haproxy.v1.HAProxyManagerService.GetServer:input_type -> haproxy.v1.GetServerRequest
	22, // 22: haproxy.v1.HAProxyManagerService.ListServers:input_type -> haproxy.v1.ListServersRequest
	23, // 23: haproxy.v1.HAProxyManagerService.UpdateServer:input_type -> haproxy.v1.UpdateServerRequest
	24, // 24: haproxy.v1.HAProxyManagerService.DeleteServer:input_type -> haproxy.v1.DeleteServerRequest
	25, // 25: haproxy.v1.HAProxyManagerService.GetVersion:output_type -> haproxy.v1.GetVersionResponse
	26, // 26: haproxy.v1.HAProxyManagerService.CreateTransaction:output_type -> haproxy.v1.CreateTransactionResponse
	27, // 27: haproxy.v1.HAProxyManagerService.GetTransaction:output_type -> haproxy.v1.GetTransactionResponse
	28, // 28: haproxy.v1.HAProxyManagerService.CommitTransaction:output_type -> haproxy.v1.CommitTransactionResponse
	29, // 29: haproxy.v1.HAProxyManagerService.CloseTransaction:output_type -> haproxy.v1.CloseTransactionResponse
	30, // 30: haproxy.v1.HAProxyManagerService.CreateBackend:output_type -> haproxy.v1.CreateBackendResponse
	31, // 31: haproxy.v1.HAProxyManagerService.GetBackend:output_type -> haproxy.v1.GetBackendResponse
	32, // 32: haproxy.v1.HAProxyManagerService.ListBackends:output_type -> haproxy.v1.ListBackendsResponse
	33, // 33: haproxy.v1.HAProxyManagerService.UpdateBackend:output_type -> haproxy.v1.UpdateBackendResponse
	34, // 34: haproxy.v1.HAProxyManagerService.DeleteBackend:output_type -> haproxy.v1.DeleteBackendResponse
	35, // 35: haproxy.v1.HAProxyManagerService.CreateFrontend:output_type -> haproxy.v1.CreateFrontendResponse
	36, // 36: haproxy.v1.HAProxyManagerService.GetFrontend:output_type -> haproxy.v1.GetFrontendResponse
	37, // 37: haproxy.v1.HAProxyManagerService.ListFrontends:output_type -> haproxy.v1.ListFrontendsResponse
	38, // 38: haproxy.v1.HAProxyManagerService.UpdateFrontend:output_type -> haproxy.v1.UpdateFrontendResponse
	39, // 39: haproxy.v1.HAProxyManagerService.DeleteFrontend:output_type -> haproxy.v1.DeleteFrontendResponse
	40, // 40: haproxy.v1.HAProxyManagerService.CreateBind:output_type -> haproxy.v1.CreateBindResponse
	41, // 41: haproxy.v1.HAProxyManagerService.GetBind:output_type -> haproxy.v1.GetBindResponse
	42, // 42: haproxy.v1.HAProxyManagerService.ListBinds:output_type -> haproxy.v1.ListBindsResponse
	43, // 43: haproxy.v1.HAProxyManagerService.UpdateBind:output_type -> haproxy.v1.UpdateBindResponse
	44, // 44: haproxy.v1.HAProxyManagerService.DeleteBind:output_type -> haproxy.v1.DeleteBindResponse
	45, // 45: haproxy.v1.HAProxyManagerService.CreateServer:output_type -> haproxy.v1.CreateServerResponse
	46, // 46: haproxy.v1.HAProxyManagerService.GetServer:output_type -> haproxy.v1.GetServerResponse
	47, // 47: haproxy.v1.HAProxyManagerService.ListServers:output_type -> haproxy.v1.ListServersResponse
	48, // 48: haproxy.v1.HAProxyManagerService.UpdateServer:output_type -> haproxy.v1.UpdateServerResponse
	49, // 49: haproxy.v1.HAProxyManagerService.DeleteServer:output_type -> haproxy.v1.DeleteServerResponse
	25, // [25:50] is the sub-list for method output_type
	0,  // [0:25] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_haproxy_proto_init() }
func file_haproxy_proto_init() {
	if File_haproxy_proto != nil {
		return
	}
	file_transaction_proto_init()
	file_backend_proto_init()
	file_frontend_proto_init()
	file_bind_proto_init()
	file_server_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_haproxy_proto_rawDesc), len(file_haproxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_haproxy_proto_goTypes,
		DependencyIndexes: file_haproxy_proto_depIdxs,
	}.Build()
	File_haproxy_proto = out.File
	file_haproxy_proto_goTypes = nil
	file_haproxy_proto_depIdxs = nil
}
